# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from service.service_spec import example_executable_service_pb2 as service_dot_service__spec_dot_example__executable__service__pb2


class AdditionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.add = channel.unary_unary(
        '/Addition/add',
        request_serializer=service_dot_service__spec_dot_example__executable__service__pb2.Numbers.SerializeToString,
        response_deserializer=service_dot_service__spec_dot_example__executable__service__pb2.Result.FromString,
        )


class AdditionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdditionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'add': grpc.unary_unary_rpc_method_handler(
          servicer.add,
          request_deserializer=service_dot_service__spec_dot_example__executable__service__pb2.Numbers.FromString,
          response_serializer=service_dot_service__spec_dot_example__executable__service__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Addition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
